#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Quota
Version  : 1.7.2
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOMZO/Quota-1.7.2.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOMZO/Quota-1.7.2.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libq/libquota-perl/libquota-perl_1.7.2+dfsg-1.debian.tar.xz
Summary  : Quota - Perl interface to file system quotas
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Quota-lib
Requires: perl-Quota-man

%description
Quota extension module for Perl
-------------------------------
Author:    Tom Zoerner (tomzo AT users.sourceforge.net)

%package lib
Summary: lib components for the perl-Quota package.
Group: Libraries

%description lib
lib components for the perl-Quota package.


%package man
Summary: man components for the perl-Quota package.
Group: Default

%description man
man components for the perl-Quota package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Quota-1.7.2
mkdir -p %{_topdir}/BUILD/Quota-1.7.2/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Quota-1.7.2/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/Quota.pm
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Quota/autosplit.ix

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi/auto/Quota/Quota.so

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Quota.3
